import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent

# Directories to exclude (per Stefan's guidance)
EXCLUDED_DIRS = [
    "system-tables",
    "error-codes",
    "clientserver-protocol",
    "product-development",
]

# Maps directory path segments to help_category_id from mysql.help_category
CATEGORY_MAP = {
    "string-functions": 37,
    "aggregate-functions": 16,
    "numeric-functions": 4,
    "date-time-functions": 31,
    "control-flow-functions": 7,
    "encryption-functions": 12,
    "information-functions": 17,
    "bit-functions": 19,
    "miscellaneous-functions": 14,
    "data-types": 22,
    "plugins": 5,
    "stored-procedures": 33,
    "stored-functions": 33,
    "stored-routines": 33,
    "transactions": 8,
    "data-definition": 39,
    "data-manipulation": 27,
    "account-management": 10,
    "geometry": 34,
    "geometry-constructors": 24,
    "geometry-properties": 36,
    "geometry-relations": 30,
    "sql-language-structure": 29,
    "operators": 38,
    "comparison-operators": 18,
    "logical-operators": 15,
    "user-defined-functions": 21,
    "table-maintenance": 20,
    "administrative": 26,
}

# Static help_category definitions (id, name, parent_category_id, url)
HELP_CATEGORIES = [
    (1, 'Geographic', 0, ''),
    (2, 'Polygon properties', 34, ''),
    (3, 'WKT', 34, ''),
    (4, 'Numeric Functions', 38, ''),
    (5, 'Plugins', 35, ''),
    (6, 'MBR', 34, ''),
    (7, 'Control flow functions', 38, ''),
    (8, 'Transactions', 35, ''),
    (9, 'Help Metadata', 35, ''),
    (10, 'Account Management', 35, ''),
    (11, 'Point properties', 34, ''),
    (12, 'Encryption Functions', 38, ''),
    (13, 'LineString properties', 34, ''),
    (14, 'Miscellaneous Functions', 38, ''),
    (15, 'Logical operators', 38, ''),
    (16, 'Functions and Modifiers for Use with GROUP BY', 35, ''),
    (17, 'Information Functions', 38, ''),
    (18, 'Comparison operators', 38, ''),
    (19, 'Bit Functions', 38, ''),
    (20, 'Table Maintenance', 35, ''),
    (21, 'User-Defined Functions', 35, ''),
    (22, 'Data Types', 35, ''),
    (23, 'Compound Statements', 35, ''),
    (24, 'Geometry constructors', 34, ''),
    (25, 'GeometryCollection properties', 1, ''),
    (26, 'Administration', 35, ''),
    (27, 'Data Manipulation', 35, ''),
    (28, 'Utility', 35, ''),
    (29, 'Language Structure', 35, ''),
    (30, 'Geometry relations', 34, ''),
    (31, 'Date and Time Functions', 38, ''),
    (32, 'WKB', 34, ''),
    (33, 'Procedures', 35, ''),
    (34, 'Geographic Features', 35, ''),
    (35, 'Contents', 0, ''),
    (36, 'Geometry properties', 34, ''),
    (37, 'String Functions', 38, ''),
    (38, 'Functions', 35, ''),
    (39, 'Data Definition', 35, ''),
]

SQL_PREAMBLE = """\
-- Copyright (c) 2003, 2008-2012, Oracle and/or its affiliates. All rights reserved.
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; version 2 of the License.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

-- DO NOT EDIT THIS FILE. It is generated automatically.

-- To use this file, load its contents into the mysql database. For example,
-- with the mysql client program, process the file like this, where
-- file_name is the name of this file:

--     mysql -u root -p mysql < file_name

set names 'utf8';

set sql_log_bin = 0;

use mysql;
delete from help_topic;
delete from help_category;
delete from help_keyword;
delete from help_relation;
"""

def get_category_id(path: str) -> int:
    """Match directory path to category ID. Returns 35 (Contents) if no match."""
    for key, cat_id in CATEGORY_MAP.items():
        if key in path:
            return cat_id
    return 35  # Default: Contents


def extract_keywords(name):
    """Extract keyword tokens from a topic name for help_keyword entries."""
    clean_name = name.replace('\\', '')
    words = re.split(r'[\s,/]+', clean_name)
    keywords = [w.upper() for w in words if len(w.strip()) > 0]
    return keywords


def get_files(base_path: str = "server/reference") -> list:
    """Find all .md files in base_path, excluding EXCLUDED_DIRS and empty READMEs."""
    files = []
    base = Path(base_path)
    
    for md_file in base.rglob("*.md"):
        path_str = str(md_file)
        
        # Skip excluded directories
        if any(excluded in path_str for excluded in EXCLUDED_DIRS):
            continue
        
        # Skip READMEs that are empty or near-empty (≤3 lines)
        if md_file.name == "README.md":
            try:
                line_count = sum(1 for _ in open(md_file, 'r', encoding='utf-8'))
                if line_count <= 3:
                    continue
            except Exception:
                continue
            
        files.append(path_str)
    
    return sorted(files)


def open_file(file_path: str):
    with open(file_path, 'r', encoding='utf-8') as file:
        return file.read().splitlines()

    
def find_line_range(data: list):
    start = None
    end = None
    name = None
    data_length = len(data)
    
    for line in range(data_length):
        if data[line].startswith("# "):
            start = line
            name = data[line].lstrip("# ")
            break
    
    if start is None:
        return None, None
    
    see_also_pattern = re.compile(r'^#{2,}\s*see\s+also', re.IGNORECASE)
    
    for line in range(start, data_length):
        if (see_also_pattern.match(data[line]) 
            or data[line].lower().startswith("{% @marketo/form") 
            or data[line].lower().startswith("<sub>")):
            end = line
            break
    
    if end is None:
        end = data_length
    
    content = data[start:end]
    return content, name


def extract_sections(content: list):
    syntax_start = None
    desc_start = None
    example_start = None
    
    syntax_pattern = re.compile(r'^#{2,}\s*syntax', re.IGNORECASE)
    desc_pattern = re.compile(r'^#{2,}\s*(description|overview)', re.IGNORECASE)
    example_pattern = re.compile(r'^#{2,}\s*examples?', re.IGNORECASE)
    
    for line in range(len(content)):
        if syntax_pattern.match(content[line]):
            syntax_start = line
        elif desc_pattern.match(content[line]) and desc_start is None:
            desc_start = line
        elif example_pattern.match(content[line]) and example_start is None:
            example_start = line

    # Standard case: has Syntax and Description/Overview
    if syntax_start is not None and desc_start is not None:
        syntax = content[syntax_start:desc_start]
        syntax_content = extract_code_block(syntax)
        if example_start:
            desc = content[desc_start+1:example_start]
        else:
            desc = content[desc_start+1:]
    # Has Description/Overview but no Syntax
    elif desc_start is not None:
        syntax_content = []
        if example_start:
            desc = content[desc_start+1:example_start]
        else:
            desc = content[desc_start+1:]
    # Fallback: no Syntax, no Description - use prose after title
    else:
        syntax_content = []
        if example_start:
            desc = content[1:example_start]  # Skip title line
        else:
            desc = content[1:]  # Everything after title
    
    # Extract example code block
    example_content = extract_code_block(content[example_start+1:] if example_start else [])
    
    # Return syntax and description separately
    syntax_str = "\n".join(syntax_content) if syntax_content else ""
    desc_str = "\n".join(desc)
 
    return syntax_str, desc_str, example_content


def extract_code_block(lines: list):
    start = None
    stop = None
    
    for i in range(len(lines)):
        if lines[i] == "```sql" and start is None:
            start = i
        elif lines[i] == "```" and start is not None:
            stop = i
            break
    
    if start is not None and stop is not None:
        return lines[start+1:stop]
    
    return []


def strip_markdown(text: str) -> str:
    """Convert markdown to plain text for clean HELP output."""
    # Remove {% ... %} template tags (tabs, hints, etc.)
    text = re.sub(r'\{%.*?%\}', '', text)
    # Convert markdown links [text](url) to just text
    text = re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', text)
    # Remove backtick code formatting
    text = re.sub(r'`([^`]+)`', r'\1', text)
    # Remove escaped underscores
    text = text.replace('\\_', '_')
    # Remove markdown bold/italic
    text = re.sub(r'\*\*([^*]+)\*\*', r'\1', text)
    text = re.sub(r'\*([^*]+)\*', r'\1', text)
    # Remove markdown heading markers
    text = re.sub(r'^#{1,6}\s+', '', text, flags=re.MULTILINE)
    # Collapse multiple blank lines into two
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


def truncate_to_bytes(text: str, max_bytes: int = 60000) -> str:
    """Truncate a string so its UTF-8 encoding fits within max_bytes."""
    encoded = text.encode('utf8')
    if len(encoded) <= max_bytes:
        return text
    truncated = encoded[:max_bytes].decode('utf8', errors='ignore')
    return truncated.rstrip() + '\n\n[Truncated — full content at mariadb.com/docs]'

def build_output(name, syntax: str, desc: str, example: list, path: str):
    parts = []
    if syntax:
        parts.append(f"Syntax\n------\n\n{syntax}")
    if desc.strip():
        parts.append(f"Description\n-----------\n\n{desc}")
    if example:
        example_str = "\n".join(example)
        parts.append(f"Examples\n--------\n\n{example_str}")
    desc_str = "\n\n".join(parts) if parts else ""
    desc_str = strip_markdown(desc_str)
    url_path = path.removesuffix(".md")
    url = f"https://mariadb.com/docs/{url_path}"
    desc_str += f"\n\nURL: {url}"
    desc_str = truncate_to_bytes(desc_str)

    if len(name) > 64:
        name = name[:64]

    content = {
        "name": name,
        "description": desc_str, 
        "example": "", 
        "url": url,
    }

    return content

def escape_sql(text):
    # Escape backslashes first, then single quotes, then newlines
    text = text.replace("\\", "\\\\")
    text = text.replace("'", "''")
    text = text.replace("\n", "\\n")
    return text

def generate_insert(name, description, example, help_topic_id, url, help_category_id):

    sql = (
        f"INSERT INTO help_topic (help_topic_id, help_category_id, name, description, example, url) "
        f"VALUES ({help_topic_id}, {help_category_id}, '{name}', '{description}', '{example}', '{url}');"
    )
    return sql


def process_single_file(path: str, help_topic_id: int) -> dict:
    """Process a single file and return topic dict or None on failure."""
    try:
        data = open_file(path)
        content, name = find_line_range(data)
        
        if content is None:
            return None
            
        syntax, desc, example = extract_sections(content)
        
        # Skip files with no meaningful content
        desc_stripped = desc.strip()
        if not desc_stripped and not example:
            return None
        
        full_content = build_output(name, syntax, desc, example, path)

        name_ = escape_sql(full_content["name"])
        description_ = escape_sql(full_content["description"])
        example_ = escape_sql(full_content["example"])
        url_ = escape_sql(full_content["url"])
        category_id = get_category_id(path)
        
        sql = generate_insert(name_, description_, example_, help_topic_id, url_, category_id)
        return {
            'sql': sql,
            'topic_id': help_topic_id,
            'name': full_content['name'],
        }
        
    except Exception as e:
        print(f"Failed to parse {path}: {e}")
        return None


def process_batch(file_list: list, start_id: int = 0) -> list:
    """Process all files and return list of topic dicts."""
    topics = []
    seen_names = set()
    help_topic_id = start_id
    failed = []
    
    for path in file_list:
        result = process_single_file(path, help_topic_id)
        if result:
            name_lower = result['name'].lower()
            if name_lower in seen_names:
                failed.append(path)
                continue
            seen_names.add(name_lower)
            topics.append(result)
            help_topic_id += 1
        else:
            failed.append(path)
    
    print(f"Processed: {len(topics)} files")
    print(f"Failed: {len(failed)} files")
    
    return topics, failed


def generate_category_inserts():
    """Generate INSERT statements for help_category."""
    inserts = []
    for cat_id, name, parent_id, url in HELP_CATEGORIES:
        escaped_name = name.replace("'", "''")
        inserts.append(
            f"insert into help_category (help_category_id,name,parent_category_id,url) "
            f"values ({cat_id},'{escaped_name}',{parent_id},'{url}');"
        )
    return inserts


def build_keywords_and_relations(topics):
    """Build help_keyword and help_relation data from processed topics.
    
    Returns:
        keyword_inserts: list of SQL INSERT statements for help_keyword
        relation_inserts: list of SQL INSERT statements for help_relation
    """
    keyword_to_id = {}
    next_keyword_id = 0
    relations = []
    seen_relations = set()
    
    for topic in topics:
        name = topic['name']
        topic_id = topic['topic_id']
        keywords = extract_keywords(name)
        
        for kw in keywords:
            if kw not in keyword_to_id:
                keyword_to_id[kw] = next_keyword_id
                next_keyword_id += 1
            pair = (topic_id, keyword_to_id[kw])
            if pair not in seen_relations:
                seen_relations.add(pair)
                relations.append(pair)
    
    keyword_inserts = []
    for kw, kid in sorted(keyword_to_id.items(), key=lambda x: x[1]):
        escaped_kw = kw.replace("'", "''")
        keyword_inserts.append(
            f"insert into help_keyword (help_keyword_id,name) values ({kid},'{escaped_kw}');"
        )
    
    relation_inserts = []
    for topic_id, keyword_id in relations:
        relation_inserts.append(
            f"insert into help_relation (help_topic_id,help_keyword_id) values ({topic_id},{keyword_id});"
        )
    
    return keyword_inserts, relation_inserts


def write_output(topics: list, output_file: str = "fill_help_tables.sql"):
    """Write the complete fill_help_tables.sql file."""
    category_inserts = generate_category_inserts()
    topic_inserts = [t['sql'] for t in topics]
    keyword_inserts, relation_inserts = build_keywords_and_relations(topics)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(SQL_PREAMBLE)
        f.write('\n')
        for stmt in category_inserts:
            f.write(stmt + '\n')
        f.write('\n')
        for stmt in topic_inserts:
            f.write(stmt + '\n')
        f.write('\n')
        for stmt in keyword_inserts:
            f.write(stmt + '\n')
        f.write('\n')
        for stmt in relation_inserts:
            f.write(stmt + '\n')
    
    print(f"Written to {output_file}")
    print(f"  Categories: {len(category_inserts)}")
    print(f"  Topics: {len(topic_inserts)}")
    print(f"  Keywords: {len(keyword_inserts)}")
    print(f"  Relations: {len(relation_inserts)}")


def main():
    # Get all files to process
    files = get_files(str(REPO_ROOT / "server" / "reference"))
    print(f"Found {len(files)} files to process")
    
    # Process all files
    topics, failed = process_batch(files)
    
    # Write complete output
    output_file = str(SCRIPT_DIR / "fill_help_tables.sql")
    write_output(topics, output_file)
    
    # Optionally write failed files for review
    if failed:
        failed_file = str(SCRIPT_DIR / "failed_files.txt")
        with open(failed_file, 'w') as f:
            for path in failed:
                f.write(path + "\n")
        print(f"Failed files written to {failed_file}")


if __name__ == "__main__":
    main()